#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint
lint_exit_code=$?

if [ $lint_exit_code -ne 0 ]; then
  echo "Lint failed. Commit aborted."
  exit $lint_exit_code
fi

npm test
test_exit_code=$?

if [ $test_exit_code -ne 0 ]; then
  echo "Tests failed. Commit aborted."
  exit $test_exit_code
fi
